In [0]:
!pip install boto3

Requirement already satisfied: boto3 in /databricks/python3/lib/python3.9/site-packages (1.21.32)
Requirement already satisfied: botocore<1.25.0,>=1.24.32 in /databricks/python3/lib/python3.9/site-packages (from boto3) (1.24.32)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /databricks/python3/lib/python3.9/site-packages (from boto3) (0.5.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /databricks/python3/lib/python3.9/site-packages (from boto3) (0.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /databricks/python3/lib/python3.9/site-packages (from botocore<1.25.0,>=1.24.32->boto3) (2.8.2)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /databricks/python3/lib/python3.9/site-packages (from botocore<1.25.0,>=1.24.32->boto3) (1.26.9)
Requirement already satisfied: six>=1.5 in /databricks/python3/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.25.0,>=1.24.32->boto3) (1.16.0)
WARNING: You are using pip version 21.2.4; however, version 24.2 is available.
You should consider upgrading via the '/local_disk0/.ephemeral_nfs/envs/pythonEnv-921a0852-ae8a-4bab-baaa-d56a2fcbba88/bin/python -m pip install --upgrade pip' command.

In [0]:
import boto3
from botocore.exceptions import NoCredentialsError

# Replace with your AWS access key and secret key
aws_access_key = 'accesskey'
aws_secret_key = 'secretkey'

# Create an S3 client
s3 = boto3.client('s3',
                  aws_access_key_id=aws_access_key,
                  aws_secret_access_key=aws_secret_key)

In [0]:
import pandas as pd
from io import StringIO

In [0]:
# Define your bucket and file information for 1 file
  # Replace with your CSV file path in the bucket

bucket_name = 'ipldatasetnw123'
file_key = 'IPLDataSet.csv'

# Get the object from S3
csv_obj = s3.get_object(Bucket=bucket_name, Key=file_key)

# Read the content of the file
body = csv_obj['Body'].read().decode('utf-8')

# Use StringIO to load the CSV content into pandas
csv_string_io = StringIO(body)
df = pd.read_csv(csv_string_io)

# Display the DataFrame
print(df.head())

   MatcH_id  Over_id  Ball_id  Innings_No Team_Batting Team_Bowling  \
0    598028       15        6           1            5            2
1    598028       14        1           1            5            2
2    598028       14        2           1            5            2
3    598028       14        3           1            5            2
4    598028       14        4           1            5            2

   Striker_Batting_Position Extra_Type  Runs_Scored  Extra_runs  ...  \
0                       6.0  No Extras            4           0  ...
1                       5.0  No Extras            1           0  ...
2                       3.0  No Extras            1           0  ...
3                       5.0  No Extras            1           0  ...
4                       3.0  No Extras            0           0  ...

   Fielder_match_SK  Fielder_SK  Bowler_match_SK  BOWLER_SK  \
0                -1          -1            20343         82
1                -1          -1            20348        345
2                -1          -1            20348        345
3                -1          -1            20348        345
4                -1          -1            20348        345

   PlayerOut_match_SK  BattingTeam_SK BowlingTeam_SK  Keeper_Catch  \
0                  -1               4              1             0
1                  -1               4              1             0
2                  -1               4              1             0
3                  -1               4              1             0
4                  -1               4              1             0

   Player_out_sk  MatchDateSK
0              0     20130420
1              0     20130420
2              0     20130420
3              0     20130420
4              0     20130420

[5 rows x 48 columns]

In [0]:
# List of file keys you want to download from S3
file_keys = ['IPLDataSet_ballbyball.csv', 'IPLDataSet_match.csv', 'IPLDataSet_playermatch.csv', 'IPLDataSet_player.csv', 'IPLDataSet_team.csv']  

# Loop through each file key and load it into a DataFrame
for file_key in file_keys:
    try:
        # Get the object from S3
        csv_obj = s3.get_object(Bucket=bucket_name, Key=file_key)

        # Read the content of the file
        body = csv_obj['Body'].read().decode('utf-8')

        # Use StringIO to load the CSV content into pandas
        csv_string_io = StringIO(body)
        df = pd.read_csv(csv_string_io)

        # Get the base filename without the extension
        base_filename = os.path.splitext(file_key)[0]

        # Store the DataFrame in the global scope with the base filename as the variable name
        globals()[base_filename] = df
        
        # Display the DataFrame
        print(f"Data from {base_filename}:")
        print(df.head())
        
    except Exception as e:
        print(f"Failed to load {file_key}: {str(e)}")

Data from IPLDataSet_ballbyball:
   MatcH_id  Over_id  Ball_id  Innings_No Team_Batting Team_Bowling  \
0    598028       15        6           1            5            2
1    598028       14        1           1            5            2
2    598028       14        2           1            5            2
3    598028       14        3           1            5            2
4    598028       14        4           1            5            2

   Striker_Batting_Position Extra_Type  Runs_Scored  Extra_runs  ...  \
0                       6.0  No Extras            4           0  ...
1                       5.0  No Extras            1           0  ...
2                       3.0  No Extras            1           0  ...
3                       5.0  No Extras            1           0  ...
4                       3.0  No Extras            0           0  ...

   Fielder_match_SK  Fielder_SK  Bowler_match_SK  BOWLER_SK  \
0                -1          -1            20343         82
1                -1          -1            20348        345
2                -1          -1            20348        345
3                -1          -1            20348        345
4                -1          -1            20348        345

   PlayerOut_match_SK  BattingTeam_SK BowlingTeam_SK  Keeper_Catch  \
0                  -1               4              1             0
1                  -1               4              1             0
2                  -1               4              1             0
3                  -1               4              1             0
4                  -1               4              1             0

   Player_out_sk  MatchDateSK
0              0     20130420
1              0     20130420
2              0     20130420
3              0     20130420
4              0     20130420

[5 rows x 48 columns]
Data from IPLDataSet_match:
   Match_SK  match_id                        Team1  \
0         0    335987  Royal Challengers Bangalore
1         1    335988              Kings XI Punjab
2         2    335989             Delhi Daredevils
3         3    335990               Mumbai Indians
4         4    335991        Kolkata Knight Riders

                         Team2 match_date  Season_Year  \
0        Kolkata Knight Riders  4/18/2008         2008
1          Chennai Super Kings  4/19/2008         2008
2             Rajasthan Royals  4/19/2008         2008
3  Royal Challengers Bangalore  4/20/2008         2008
4              Deccan Chargers  4/20/2008         2008

                                   Venue_Name   City_Name Country_Name  \
0                       M Chinnaswamy Stadium   Bangalore        India
1  Punjab Cricket Association Stadium, Mohali  Chandigarh        India
2                            Feroz Shah Kotla       Delhi        India
3                            Wankhede Stadium      Mumbai        India
4                                Eden Gardens     Kolkata        India

                   Toss_Winner                 match_winner Toss_Name  \
0  Royal Challengers Bangalore        Kolkata Knight Riders     field
1          Chennai Super Kings          Chennai Super Kings       bat
2             Rajasthan Royals             Delhi Daredevils       bat
3               Mumbai Indians  Royal Challengers Bangalore       bat
4              Deccan Chargers        Kolkata Knight Riders       bat

  Win_Type Outcome_Type    ManOfMach  Win_Margin  Country_id
0     runs       Result  BB McCullum       140.0           1
1     runs       Result   MEK Hussey        33.0           1
2  wickets       Result  MF Maharoof         9.0           1
3  wickets       Result   MV Boucher         5.0           1
4  wickets       Result    DJ Hussey         5.0           1
Data from IPLDataSet_playermatch:
   Player_match_SK  PlayerMatch_key  Match_Id  Player_Id Player_Name  \
0               -1    -1.000000e+00        -1         -1         NaN
1            12694     3.359870e+10    335987          6    R Dravid
2            12695     3.359870e+10    335987          7    W Jaffer
3            12696     3.359870e+10    335987          8     V Kohli
4            12697     3.359870e+10    335987          9   JH Kallis

          DOB    Batting_hand          Bowling_skill  Country_Name Role_Desc  \
0         NaN             NaN                    NaN           NaN       NaN
1   1/11/1973  Right-hand bat     Right-arm offbreak         India   Captain
2   2/16/1978  Right-hand bat     Right-arm offbreak         India    Player
3   11/5/1988  Right-hand bat       Right-arm medium         India    Player
4  10/16/1975  Right-hand bat  Right-arm fast-medium  South Africa    Player

   ... Season_year is_manofThematch  Age_As_on_match  IsPlayers_Team_won  \
0  ...         NaN              NaN              NaN                 NaN
1  ...      2008.0              0.0             35.0                 0.0
2  ...      2008.0              0.0             30.0                 0.0
3  ...      2008.0              0.0             20.0                 0.0
4  ...      2008.0              0.0             33.0                 0.0

   Batting_Status  Bowling_Status  Player_Captain  Opposit_captain  \
0             NaN             NaN             NaN              NaN
1             NaN             NaN        R Dravid       SC Ganguly
2             NaN             NaN        R Dravid       SC Ganguly
3             NaN             NaN        R Dravid       SC Ganguly
4             NaN             NaN        R Dravid       SC Ganguly

  Player_keeper Opposit_keeper
0           NaN            NaN
1    MV Boucher        WP Saha
2    MV Boucher        WP Saha
3    MV Boucher        WP Saha
4    MV Boucher        WP Saha

[5 rows x 22 columns]
Data from IPLDataSet_player:
   PLAYER_SK  Player_Id      Player_Name         DOB    Batting_hand  \
0          0          1       SC Ganguly    7/8/1972   Left-hand bat
1          1          2      BB McCullum   9/27/1981  Right-hand bat
2          2          3       RT Ponting  12/19/1974  Right-hand bat
3          3          4        DJ Hussey   7/15/1977  Right-hand bat
4          4          5  Mohammad Hafeez  10/17/1980  Right-hand bat

        Bowling_skill Country_Name
0    Right-arm medium        India
1    Right-arm medium  New Zealand
2    Right-arm medium    Australia
3  Right-arm offbreak    Australia
4  Right-arm offbreak     Pakistan
Data from IPLDataSet_team:
   Team_SK  Team_Id                    Team_Name
0        0        1        Kolkata Knight Riders
1        1        2  Royal Challengers Bangalore
2        2        3          Chennai Super Kings
3        3        4              Kings XI Punjab
4        4        5             Rajasthan Royals

In [0]:
IPLDataSet_ballbyball.head(2)

,MatcH_id,Over_id,Ball_id,Innings_No,Team_Batting,Team_Bowling,Striker_Batting_Position,Extra_Type,Runs_Scored,Extra_runs,...,Fielder_match_SK,Fielder_SK,Bowler_match_SK,BOWLER_SK,PlayerOut_match_SK,BattingTeam_SK,BowlingTeam_SK,Keeper_Catch,Player_out_sk,MatchDateSK
0,598028,15,6,1,5,2,6.0,No Extras,4,0,...,-1,-1,20343,82,-1,4,1,0,0,20130420
1,598028,14,1,1,5,2,5.0,No Extras,1,0,...,-1,-1,20348,345,-1,4,1,0,0,20130420

In [0]:
IPLDataSet_match.head()

,Match_SK,match_id,Team1,Team2,match_date,Season_Year,Venue_Name,City_Name,Country_Name,Toss_Winner,match_winner,Toss_Name,Win_Type,Outcome_Type,ManOfMach,Win_Margin,Country_id
0,0,335987,Royal Challengers Bangalore,Kolkata Knight Riders,4/18/2008,2008,M Chinnaswamy Stadium,Bangalore,India,Royal Challengers Bangalore,Kolkata Knight Riders,field,runs,Result,BB McCullum,140.0,1
1,1,335988,Kings XI Punjab,Chennai Super Kings,4/19/2008,2008,"Punjab Cricket Association Stadium, Mohali",Chandigarh,India,Chennai Super Kings,Chennai Super Kings,bat,runs,Result,MEK Hussey,33.0,1
2,2,335989,Delhi Daredevils,Rajasthan Royals,4/19/2008,2008,Feroz Shah Kotla,Delhi,India,Rajasthan Royals,Delhi Daredevils,bat,wickets,Result,MF Maharoof,9.0,1
3,3,335990,Mumbai Indians,Royal Challengers Bangalore,4/20/2008,2008,Wankhede Stadium,Mumbai,India,Mumbai Indians,Royal Challengers Bangalore,bat,wickets,Result,MV Boucher,5.0,1
4,4,335991,Kolkata Knight Riders,Deccan Chargers,4/20/2008,2008,Eden Gardens,Kolkata,India,Deccan Chargers,Kolkata Knight Riders,bat,wickets,Result,DJ Hussey,5.0,1